### PR TITLE
Improve TF docs generation

### PR DESCRIPTION
**Pull request by ellismg**
- Don't drop URLs to documentation when the content has been elided.
- Don't write a source file named after the package itself, this is likely to conflict with resources in the package.

### CODE REVIEW

**Comment by ellismg** [comment]
CI is failing because Azure is failing to build, since some of my workarounds for the filename bug are no longer needed.

**Comment by ellismg** [comment]
The source diffs show some comments being dropped for strange reasons I do not fully understand yet.  I still think we want to take these changes because they are an overall improvement.  I filed https://github.com/pulumi/pulumi-terraform/issues/410 to track the open issue.

**Comment by ellismg** [comment]
The build failures in azure are due to the d69ef52.  This is actually the right thing to do.  We just need to remove these lines from the `Makefile`'s when we flow this to other repositories:

https://github.com/pulumi/pulumi-azure/blob/master/Makefile#L23-L27
https://github.com/pulumi/pulumi-openstack/blob/master/Makefile#L25-L27

/cc @stack72

**Comment by stack72** [comment]
Sounds good @ellismg - if you are happy let's merge, I can go ahead and update AWS and OpenStack based on this?

**Comment by ellismg** [comment]
> Sounds good @ellismg - if you are happy let's merge, I can go ahead and update AWS and OpenStack based on this?

SGTM.  Tag me on the reviews, and I'll take a look shortly.

**Pull request merged**
