### PR TITLE
Add -allow-missing-plugins to tf2pulumi calls

### PR DESCRIPTION
**Pull request by jen20**
This contributes to fixing #306.

### CODE REVIEW

**Comment by joeduffy** [comment]
I am not an expert on this, so will want @pat to weigh in.

My only worry here is that this might lead to different code-gen locally versus on Travis, still, because when the plugin is missing we won't use our name-mappings from the plugin. I think this might lead to names like `some_random_property`, rather than `someRandomProperty`.

Unfortunately, I don't have a great "alternative" to suggest. One idea is to pass an explicit set of providers at the command line to use, and tell `tf2pulumi` to skip anything outside of that set. Then for, say, Azure, we'd pass `--plugins=/path/to/pulumi-resource-azure`, and that's all that it would use.

**Comment by pgavlin** [comment]
> Unfortunately, I don't have a great "alternative" to suggest. One idea is to pass an explicit set of providers at the command line to use, and tell tf2pulumi to skip anything outside of that set.

I think that we should do this.

We could also have Travis install a select set of basic plugins (`random` and `template` come to mind) if the examples that fail generation due to those plugins are high-value.

**Comment by lukehoban** [comment]
>  degrades the generated code

Does it really degrade the generated code in these cases, or just allow examples which are "incomplete" to still codegen?

**Comment by joeduffy** [comment]
Won't it still be different on dev versus Travis machines? Uses the plugin on one, degraded code on the other? We may get lucky for the current example set but it would seem this is a lurking issue...

**Comment by pgavlin** [comment]
> Does it really degrade the generated code in these cases, or just allow examples which are "incomplete" to still codegen?

It does degrade the code: any uses of resources managed by a missing provider will look a bit weird due to missing type information. I don't have an example on hand, but names especially can be strange.

> Won't it still be different on dev versus Travis machines? Uses the plugin on one, degraded code on the other?

Yes, it will. I do think that we should do the thing you suggested earlier and add a command-line flag to limit the plugins available to `tf2pulumi`.

**Comment by joeduffy** [comment]
LGTM. Now that we have a workaround for the plugin references, are we good to merge this?

Once we do, I'll re-gen the docs website.

**Comment by jen20** [comment]
We came up with an alternative to merging that, which is to install the necessary plugins in the Makefile of each particular provider. I think it's better to fail the build as new providers are required and for us to update the Makefile in response vs allowing worse docs to slide through.

**Pull request closed without merging**
