### PR TITLE
.NET namespace capitalization

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Tested with AzureAD and Azure overrides:
- https://github.com/pulumi/pulumi-azuread/pull/39
- https://github.com/pulumi/pulumi-azure/pull/402

cc @pgavlin

### CODE REVIEW

**Comment by lukehoban** [comment]
I feel like we probably need to do something more robust - effectively require every provider to provide every namespace in both TitleCase and lowercase. (Or perhaps even switch to just TitleCase and derive all other forms from that?)

Because it is a breaking change to change these - I do not think we should allow a fallback - we should require that an explicit (or reliably derivable) name is supplied.

**Comment by pgavlin** [comment]
> (Or perhaps even switch to just TitleCase and derive all other forms from that?)

This is what I was thinking, personally.

**Comment by CyrusNajmabadi** [comment]
I'm moving forward with this.

**Comment by CyrusNajmabadi** [comment]
Tracking issue for a better solution is here: https://github.com/pulumi/pulumi-terraform/issues/511

**Pull request merged**
